import { createFileRoute, redirect } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { AdminLayout } from '../../components/layout/AdminLayout'
import { DataTable } from '../../components/ui/DataTable'
import type { Column } from '../../components/ui/DataTable'
import { StatusBadge } from '../../components/ui/StatusBadge'
import { SearchInput } from '../../components/ui/SearchInput'
import { FileText, Download } from 'lucide-react'
import { walletApi } from '../../lib/api'
import { format } from 'date-fns'
import { APP_NAME } from '../../lib/constants'

export const Route = createFileRoute('/reports/')({
  beforeLoad: () => {
    if (typeof window !== 'undefined') {
      const token = sessionStorage.getItem('admin_token')
      if (!token) {
        throw redirect({ to: '/login' })
      }
    }
  },
  head: () => ({
    meta: [
      { title: `Reports - ${APP_NAME}` },
      { name: 'description', content: 'View platform reports' },
    ],
  }),
  component: ReportsPage,
})

interface Report {
  id: string
  type: string
  title: string
  description?: string
  status: string
  file_url?: string
  created_at: string
  user?: {
    email: string
    first_name: string
    last_name: string
  }
}

function ReportsPage() {
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const limit = 20

  const { data, isLoading } = useQuery({
    queryKey: ['admin-reports', page, search],
    queryFn: async () => {
      const response = await walletApi.get('/api/reports', {
        params: { page, limit, search: search || undefined },
      })
      return response.data.data
    },
  })

  const reports: Report[] = data?.data || []
  const total = data?.pagination?.total || reports.length
  const totalPages = Math.ceil(total / limit) || 1

  const columns: Column<Report>[] = [
    {
      key: 'title',
      header: 'Report',
      render: (row) => (
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-vellum rounded-lg flex items-center justify-center">
            <FileText className="w-4 h-4 text-ink" />
          </div>
          <div>
            <p className="text-sm font-medium">{row.title}</p>
            <p className="text-xs text-slate">{row.description || ''}</p>
          </div>
        </div>
      ),
    },
    {
      key: 'type',
      header: 'Type',
      render: (row) => (
        <span className="text-sm capitalize">{row.type}</span>
      ),
    },
    {
      key: 'user',
      header: 'Generated By',
      render: (row) => (
        <div>
          <p className="text-sm font-medium">
            {row.user?.first_name} {row.user?.last_name}
          </p>
          <p className="text-xs text-slate">{row.user?.email}</p>
        </div>
      ),
    },
    {
      key: 'status',
      header: 'Status',
      render: (row) => <StatusBadge status={row.status} />,
    },
    {
      key: 'created_at',
      header: 'Created',
      render: (row) => (
        <span className="text-sm text-slate">
          {row.created_at ? format(new Date(row.created_at), 'MMM d, yyyy') : '—'}
        </span>
      ),
    },
    {
      key: 'file_url',
      header: '',
      render: (row) => (
        row.file_url ? (
          <a
            href={row.file_url}
            target="_blank"
            rel="noopener noreferrer"
            className="p-2 hover:bg-vellum rounded-lg transition-colors inline-block"
          >
            <Download className="w-4 h-4 text-ash hover:text-ink" />
          </a>
        ) : null
      ),
    },
  ]

  return (
    <AdminLayout title="Reports">
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-display text-2xl font-semibold text-ink">
              Reports
            </h2>
            <p className="text-slate mt-1">
              View and manage generated reports
            </p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <SearchInput
            value={search}
            onChange={(v) => { setSearch(v); setPage(1) }}
            placeholder="Search reports..."
            className="w-80"
          />
        </div>

        <DataTable
          columns={columns}
          data={reports}
          isLoading={isLoading}
          emptyMessage="No reports found"
          emptyIcon={<FileText className="w-8 h-8 text-ash" />}
          page={page}
          totalPages={totalPages}
          total={total}
          limit={limit}
          onPageChange={setPage}
          rowKey={(row) => row.id}
        />
      </div>
    </AdminLayout>
  )
}
