/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksIndexRouteImport } from './routes/webhooks/index'
import { Route as WalletsIndexRouteImport } from './routes/wallets/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SlackIndexRouteImport } from './routes/slack/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as PayoutsIndexRouteImport } from './routes/payouts/index'
import { Route as OtcIndexRouteImport } from './routes/otc/index'
import { Route as FeesIndexRouteImport } from './routes/fees/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as WalletsWalletIdRouteImport } from './routes/wallets/$walletId'
import { Route as UsersAddRouteImport } from './routes/users/add'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions/$transactionId'
import { Route as PayoutsPayoutIdRouteImport } from './routes/payouts/$payoutId'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIndexRoute = WebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsIndexRoute = WalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackIndexRoute = SlackIndexRouteImport.update({
  id: '/slack/',
  path: '/slack/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsIndexRoute = PayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtcIndexRoute = OtcIndexRouteImport.update({
  id: '/otc/',
  path: '/otc/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesIndexRoute = FeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsWalletIdRoute = WalletsWalletIdRouteImport.update({
  id: '/wallets/$walletId',
  path: '/wallets/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAddRoute = UsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayoutsPayoutIdRoute = PayoutsPayoutIdRouteImport.update({
  id: '/payouts/$payoutId',
  path: '/payouts/$payoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/payouts/$payoutId': typeof PayoutsPayoutIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/add': typeof UsersAddRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/fees/': typeof FeesIndexRoute
  '/otc/': typeof OtcIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/slack/': typeof SlackIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/wallets/': typeof WalletsIndexRoute
  '/webhooks/': typeof WebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/payouts/$payoutId': typeof PayoutsPayoutIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/add': typeof UsersAddRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/activity': typeof ActivityIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/fees': typeof FeesIndexRoute
  '/otc': typeof OtcIndexRoute
  '/payouts': typeof PayoutsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/slack': typeof SlackIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/users': typeof UsersIndexRoute
  '/wallets': typeof WalletsIndexRoute
  '/webhooks': typeof WebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/payouts/$payoutId': typeof PayoutsPayoutIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/add': typeof UsersAddRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/fees/': typeof FeesIndexRoute
  '/otc/': typeof OtcIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/slack/': typeof SlackIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/wallets/': typeof WalletsIndexRoute
  '/webhooks/': typeof WebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/assets/$assetId'
    | '/payouts/$payoutId'
    | '/transactions/$transactionId'
    | '/users/$userId'
    | '/users/add'
    | '/wallets/$walletId'
    | '/activity/'
    | '/assets/'
    | '/countries/'
    | '/fees/'
    | '/otc/'
    | '/payouts/'
    | '/reports/'
    | '/slack/'
    | '/transactions/'
    | '/users/'
    | '/wallets/'
    | '/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/assets/$assetId'
    | '/payouts/$payoutId'
    | '/transactions/$transactionId'
    | '/users/$userId'
    | '/users/add'
    | '/wallets/$walletId'
    | '/activity'
    | '/assets'
    | '/countries'
    | '/fees'
    | '/otc'
    | '/payouts'
    | '/reports'
    | '/slack'
    | '/transactions'
    | '/users'
    | '/wallets'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/assets/$assetId'
    | '/payouts/$payoutId'
    | '/transactions/$transactionId'
    | '/users/$userId'
    | '/users/add'
    | '/wallets/$walletId'
    | '/activity/'
    | '/assets/'
    | '/countries/'
    | '/fees/'
    | '/otc/'
    | '/payouts/'
    | '/reports/'
    | '/slack/'
    | '/transactions/'
    | '/users/'
    | '/wallets/'
    | '/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  PayoutsPayoutIdRoute: typeof PayoutsPayoutIdRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersAddRoute: typeof UsersAddRoute
  WalletsWalletIdRoute: typeof WalletsWalletIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  FeesIndexRoute: typeof FeesIndexRoute
  OtcIndexRoute: typeof OtcIndexRoute
  PayoutsIndexRoute: typeof PayoutsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SlackIndexRoute: typeof SlackIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  WalletsIndexRoute: typeof WalletsIndexRoute
  WebhooksIndexRoute: typeof WebhooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/': {
      id: '/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof WebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/': {
      id: '/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof WalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack/': {
      id: '/slack/'
      path: '/slack'
      fullPath: '/slack/'
      preLoaderRoute: typeof SlackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/': {
      id: '/payouts/'
      path: '/payouts'
      fullPath: '/payouts/'
      preLoaderRoute: typeof PayoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otc/': {
      id: '/otc/'
      path: '/otc'
      fullPath: '/otc/'
      preLoaderRoute: typeof OtcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees/': {
      id: '/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof FeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/$walletId': {
      id: '/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof WalletsWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/add': {
      id: '/users/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof UsersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/$payoutId': {
      id: '/payouts/$payoutId'
      path: '/payouts/$payoutId'
      fullPath: '/payouts/$payoutId'
      preLoaderRoute: typeof PayoutsPayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  PayoutsPayoutIdRoute: PayoutsPayoutIdRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersAddRoute: UsersAddRoute,
  WalletsWalletIdRoute: WalletsWalletIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  FeesIndexRoute: FeesIndexRoute,
  OtcIndexRoute: OtcIndexRoute,
  PayoutsIndexRoute: PayoutsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SlackIndexRoute: SlackIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  WalletsIndexRoute: WalletsIndexRoute,
  WebhooksIndexRoute: WebhooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
